export const ProductData = [
    {
        id: 1,
        title: "Ürün 1",
        image: "https://loremflickr.com/320/240?random=1",
        price: 100,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 2,
        title: "Ürün 2",
        image: "https://loremflickr.com/320/240?random=2",
        price: 200,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 3,
        title: "Ürün 3",
        image: "https://loremflickr.com/320/240?random=3",
        price: 300,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 4,
        title: "Ürün 4",
        image: "https://loremflickr.com/320/240?random=4",
        price: 400,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 5,
        title: "Ürün 5",
        image: "https://loremflickr.com/320/240?random=5",
        price: 500,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 6,
        title: "Ürün 6",
        image: "https://loremflickr.com/320/240?random=6",
        price: 600,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 7,
        title: "Ürün 7",
        image: "https://loremflickr.com/320/240?random=7",
        price: 700,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 8,
        title: "Ürün 8",
        image: "https://loremflickr.com/320/240?random=8",
        price: 800,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 9,
        title: "Ürün 9",
        image: "https://loremflickr.com/320/240?random=9",
        price: 900,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 10,
        title: "Ürün 10",
        image: "https://loremflickr.com/320/240?random=10",
        price: 1000,
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
];
